//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cbm_iso_sart_entities : DbContext
    {
        public cbm_iso_sart_entities()
            : base("name=cbm_iso_sart_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iso_cargo> iso_cargo { get; set; }
        public virtual DbSet<iso_consulta_medica> iso_consulta_medica { get; set; }
        public virtual DbSet<iso_departamento> iso_departamento { get; set; }
        public virtual DbSet<iso_empresa> iso_empresa { get; set; }
        public virtual DbSet<iso_historia_clinica> iso_historia_clinica { get; set; }
        public virtual DbSet<iso_puesto_trabajo> iso_puesto_trabajo { get; set; }
        public virtual DbSet<iso_personal> iso_personal { get; set; }
    }
}
