//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_personal
    {
        public iso_personal()
        {
            this.iso_historia_clinica = new HashSet<iso_historia_clinica>();
        }
    
        public int ipe_id_personal { get; set; }
        public string ipe_ced_ruc_personal { get; set; }
        public string ipe_nombre_personal { get; set; }
        public Nullable<System.DateTime> ipe_fecha_nacimiento { get; set; }
        public string ipe_dir_domicilio { get; set; }
        public string ipe_telf_1 { get; set; }
        public string ipe_telf_2 { get; set; }
        public string ipe_celular { get; set; }
        public Nullable<System.DateTime> ipe_fecha_ingreso { get; set; }
        public Nullable<int> ipe_id_cargo { get; set; }
        public int ipe_id_empresa { get; set; }
        public int ipe_id_departamento { get; set; }
        public string ipe_curriculum { get; set; }
        public string ipe_empresa_anterior { get; set; }
        public string ipe_descripcion_estudios { get; set; }
        public string ipe_descripcion_experiencia { get; set; }
        public byte[] ipe_archivo_curriculum { get; set; }
        public string ipe_estado_personal { get; set; }
        public Nullable<int> ipe_id_jefe { get; set; }
        public string ipe_nro_afiliacion { get; set; }
        public string ipe_genero { get; set; }
        public string ipe_profesion { get; set; }
        public string ipe_trab_habitual { get; set; }
        public Nullable<System.DateTime> ipe_horario_reg_ini { get; set; }
        public Nullable<System.DateTime> ipe_horario_reg_fin { get; set; }
        public string ipe_salario_diario { get; set; }
        public string ipe_salario_mensual { get; set; }
        public string ipe_tiempo_servicio { get; set; }
        public string ipe_estado_civil { get; set; }
        public string ipe_lugar_nacimiento { get; set; }
        public string ipe_email { get; set; }
        public string ipe_nivel_educativo { get; set; }
        public string ipe_apellido_paterno { get; set; }
        public Nullable<int> ipe_edad { get; set; }
        public string ipe_tipo_sangre { get; set; }
        public string ipe_factor_rh { get; set; }
        public string ipe_tiempo_per_a { get; set; }
        public string ipe_tiempo_per_m { get; set; }
        public string ipe_descrip_cargo { get; set; }
        public Nullable<int> ipe_id_puesto_trabajo { get; set; }
        public Nullable<bool> ipe_cambio_area { get; set; }
        public Nullable<int> ipe_id_centro_costo { get; set; }
        public string ipe_apellido_materno { get; set; }
        public string ipe_etnia { get; set; }
        public string ipe_cedula_militar { get; set; }
        public string ipe_ocupacion_anteriro { get; set; }
        public Nullable<bool> ipe_familiares_empresa { get; set; }
        public string ipe_tiene_experiencia { get; set; }
        public string ipe_nacionalidad { get; set; }
        public Nullable<bool> ipe_vulnerabilidad { get; set; }
        public string ipe_codigo_personal { get; set; }
        public byte[] ipe_foto { get; set; }
    
        public virtual iso_cargo iso_cargo { get; set; }
        public virtual iso_departamento iso_departamento { get; set; }
        public virtual iso_empresa iso_empresa { get; set; }
        public virtual ICollection<iso_historia_clinica> iso_historia_clinica { get; set; }
        public virtual iso_puesto_trabajo iso_puesto_trabajo { get; set; }
        public virtual iso_puesto_trabajo iso_puesto_trabajo1 { get; set; }
    }
}
