//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_matriz_profesiograma
    {
        public int imp_id_matrizp { get; set; }
        public int imp_id_cargo { get; set; }
        public int imp_id_area { get; set; }
        public int imp_id_puesto_trabajo { get; set; }
        public string imp_formacion { get; set; }
        public string imp_experiencia { get; set; }
        public string imp_aptitudes { get; set; }
        public string imp_actitudes { get; set; }
        public string imp_tareas_funciones { get; set; }
        public string imp_herramientas { get; set; }
        public string imp_exigencias { get; set; }
        public string imp_competencias { get; set; }
        public string imp_capacitacion { get; set; }
        public string imp_horario_trabajo { get; set; }
        public Nullable<System.DateTime> imp_fecha_creacion { get; set; }
        public string imp_preocupacional { get; set; }
        public string imp_per_reintegro { get; set; }
        public string imp_reintegro { get; set; }
        public string imp_especial { get; set; }
        public string imp_salida { get; set; }
        public string imp_absoluta { get; set; }
        public string imp_relativa { get; set; }
        public string imp_edad { get; set; }
        public string imp_genero { get; set; }
        public string imp_criterios_exclusion { get; set; }
        public string imp_conocimientos_ad { get; set; }
    
        public virtual iso_cargo iso_cargo { get; set; }
        public virtual iso_puesto_trabajo iso_puesto_trabajo { get; set; }
    }
}
