//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_antecedente_familiar
    {
        public iso_antecedente_familiar()
        {
            this.iso_ante_familiar_consulta_m = new HashSet<iso_ante_familiar_consulta_m>();
        }
    
        public int iaf_id_antecedente_familiar { get; set; }
        public string iaf_nombre_antecedente_f { get; set; }
        public string iaf_tipo_antecedente_f { get; set; }
    
        public virtual ICollection<iso_ante_familiar_consulta_m> iso_ante_familiar_consulta_m { get; set; }
    }
}
