//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_avance_plan
    {
        public long iap_id_avance_plan { get; set; }
        public System.DateTime iap_fecha_avance { get; set; }
        public int iap_id_detalle_plan { get; set; }
        public int iap_id_plan { get; set; }
        public string iap_detalle_avance { get; set; }
        public string iap_usuario_avance { get; set; }
        public string iap_porcetanje_avance { get; set; }
        public Nullable<double> iap_cantidad_avance { get; set; }
        public Nullable<double> iap_horas_avance { get; set; }
        public string iap_motivo_atraso { get; set; }
    
        public virtual iso_detalle_plan iso_detalle_plan { get; set; }
    }
}
