//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_tipo_consulta_m
    {
        public iso_tipo_consulta_m()
        {
            this.iso_consulta_medica = new HashSet<iso_consulta_medica>();
        }
    
        public int itc_id_tipo_consulta_m { get; set; }
        public string itc_nom_tipo_consulta_m { get; set; }
    
        public virtual ICollection<iso_consulta_medica> iso_consulta_medica { get; set; }
    }
}
