//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_matriz_riesgo_ocupacional
    {
        public iso_matriz_riesgo_ocupacional()
        {
            this.iso_detalle_matriz_ocupacional = new HashSet<iso_detalle_matriz_ocupacional>();
        }
    
        public int imo_id_matriz { get; set; }
        public string imo_nombre_matriz { get; set; }
        public string imo_descrip_matriz { get; set; }
        public Nullable<System.DateTime> imo_fecha_creacion { get; set; }
        public string imo_elaborado_por { get; set; }
        public Nullable<int> imo_id_personal { get; set; }
        public string imo_area_matriz { get; set; }
        public string imo_proceso_matriz { get; set; }
        public string imo_actividad_matriz { get; set; }
        public string imo_cargo_personal { get; set; }
        public string imo_puesto_trabajo { get; set; }
        public string imo_subproceso_matriz { get; set; }
        public string imo_tiempo_exposicion { get; set; }
        public Nullable<int> imo_numero_trabajadores { get; set; }
    
        public virtual ICollection<iso_detalle_matriz_ocupacional> iso_detalle_matriz_ocupacional { get; set; }
    }
}
