//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_modulo
    {
        public iso_modulo()
        {
            this.iso_usuario = new HashSet<iso_usuario>();
        }
    
        public int imd_id_modulo { get; set; }
        public string imd_nombre_modulo { get; set; }
    
        public virtual ICollection<iso_usuario> iso_usuario { get; set; }
    }
}
