//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_sintoma_consulta_m
    {
        public int isc_id_consulta_medica { get; set; }
        public int isc_id_historia_clinica { get; set; }
        public int isc_id_personal { get; set; }
        public int isc_id_sintoma { get; set; }
        public int isc_id_tipo_sintoma { get; set; }
        public string isc_tiempo_sintoma { get; set; }
        public string isc_valor_sintoma { get; set; }
    
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
        public virtual iso_sintoma iso_sintoma { get; set; }
    }
}
