//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_antecedente_personal
    {
        public iso_antecedente_personal()
        {
            this.iso_ante_personal_consulta_m = new HashSet<iso_ante_personal_consulta_m>();
        }
    
        public int iap_id_antecedente_p { get; set; }
        public string iap_nombre_antecedente_p { get; set; }
    
        public virtual ICollection<iso_ante_personal_consulta_m> iso_ante_personal_consulta_m { get; set; }
    }
}
