//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_tipo_pedido_exam
    {
        public iso_tipo_pedido_exam()
        {
            this.iso_pedido_examen = new HashSet<iso_pedido_examen>();
        }
    
        public int itp_id_tpedido_exam { get; set; }
        public string itp_nombre_tpedido { get; set; }
        public string itp_id_tpedido_padre { get; set; }
    
        public virtual ICollection<iso_pedido_examen> iso_pedido_examen { get; set; }
    }
}
