//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_pedido_exam_consulta_m
    {
        public int ipc_id_consulta_medica { get; set; }
        public int ipc_id_historia_clinica { get; set; }
        public int ipc_id_personal { get; set; }
        public int ipc_id_pexamen { get; set; }
        public int ipc_id_tipo_pexamen { get; set; }
        public string ipc_descrip { get; set; }
        public Nullable<System.DateTime> ipc_fecha { get; set; }
        public string ipc_observacion { get; set; }
        public string ipc_ubicacion_archivo { get; set; }
        public byte[] ipc_archivo { get; set; }
    
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
        public virtual iso_pedido_examen iso_pedido_examen { get; set; }
    }
}
