//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_detalle_matriz_mrl
    {
        public int idm_id_matriz_mrl { get; set; }
        public int idm_id_riesgo_mrl { get; set; }
        public int idm_id_tipo_riesgo_mrl { get; set; }
        public string idm_probabilidad { get; set; }
        public string idm_consecuencia { get; set; }
        public string idm_exposicion { get; set; }
        public string idm_resultado { get; set; }
        public string idm_valoracion_gp { get; set; }
        public string idm_descripcion { get; set; }
    
        public virtual iso_matriz_mrl iso_matriz_mrl { get; set; }
        public virtual iso_riesgo_mrl iso_riesgo_mrl { get; set; }
    }
}
