//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_accidente
    {
        public int iac_id_accidente { get; set; }
        public Nullable<int> iac_id_personal { get; set; }
        public Nullable<short> iac_cod_empresa { get; set; }
        public string iac_dia_accidente { get; set; }
        public Nullable<System.DateTime> iac_fecha_accidente { get; set; }
        public string iac_hora_accidente { get; set; }
        public string iac_sitio_accidente { get; set; }
        public string iac_descrip_accidente { get; set; }
        public string iac_lesiones_accidente { get; set; }
        public string iac_experiencia_trab { get; set; }
        public string iac_entrenamiento_trab { get; set; }
        public string iac_produjo_lesion { get; set; }
        public string iac_falla_accidente { get; set; }
        public string iac_nombres_testigos { get; set; }
        public string iac_persona_atendio { get; set; }
        public string iac_traslado_accidentado { get; set; }
    
        public virtual iso_personal iso_personal { get; set; }
    }
}
