//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iso_ante_mujer_consulta_m
    {
        public int imc_id_consulta_medica { get; set; }
        public int imc_id_historia_clinica { get; set; }
        public int imc_id_personal { get; set; }
        [Display(Name = "Antecedente Gineco Obtétrico")]
        [Required]
        public int imc_id_antecedente_mujer { get; set; }
        [Display(Name = "Diagnóstico")]
        [Required]
        public string imc_observacion { get; set; }
        public string imc_descripcion { get; set; }
        [Display(Name = "Edad")]
        [Required]
        public Nullable<int> imc_edad_mujer { get; set; }
    
        public virtual iso_antecedente_mujer iso_antecedente_mujer { get; set; }
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
    }
}
