//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iso_ante_personal_consulta_m
    {
        public int ipc_id_consulta_medica { get; set; }
        public int ipc_id_historia_clinica { get; set; }
        public int ipc_id_personal { get; set; }
        [Display(Name = "Antecedente Personal")]
        [Required]
        public int ipc_id_antecedente_p { get; set; }
        public Nullable<short> ipc_edad { get; set; }
        [Display(Name = "Diagnóstico")]
        [Required]
        public string ipc_observacion { get; set; }
    
        public virtual iso_antecedente_personal iso_antecedente_personal { get; set; }
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
    }
}
