//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_plan
    {
        public iso_plan()
        {
            this.iso_detalle_plan = new HashSet<iso_detalle_plan>();
        }
    
        public int ipl_id_plan { get; set; }
        public string ipl_tipo_plan { get; set; }
        public string ipl_nombre_plan { get; set; }
        public string ipl_descripcion_plan { get; set; }
        public Nullable<System.DateTime> ipl_fecha_creacion_plan { get; set; }
        public string ipl_creador_plan { get; set; }
        public string ipl_tolerancia { get; set; }
        public Nullable<int> ipl_responsable { get; set; }
        public string ipl_codigo_plan { get; set; }
        public Nullable<int> ipl_id_plan_padre { get; set; }
        public string ipl_tipo_proyecto { get; set; }
        public string ipl_objetivo_estrategico { get; set; }
        public Nullable<int> ipl_id_area { get; set; }
    
        public virtual ICollection<iso_detalle_plan> iso_detalle_plan { get; set; }
    }
}
