//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iso_vacuna_consulta_m
    {
        public int ivm_id_consulta_medica { get; set; }
        public int ivm_id_historia_clinica { get; set; }
        public int ivm_id_personal { get; set; }
        [Display(Name = "Antecedente de Vacuna")]
        [Required]
        public int ivm_id_vacuna { get; set; }
        [Display(Name = "Dosis")]
        [Required]
        public string ivm_dosis { get; set; }
        [Display(Name = "Diagnóstico")]
        [Required]
        public string ivm_observacion { get; set; }
    
        public virtual iso_antecedente_vacuna iso_antecedente_vacuna { get; set; }
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
    }
}
