//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_departamento
    {
        public int ide_id_departamento { get; set; }
        public string ide_nombre_departamento { get; set; }
        public string ide_descripcion_departamento { get; set; }
        public Nullable<int> ide_id_empresa { get; set; }
        public Nullable<int> ide_id_departamento_padre { get; set; }
        public Nullable<bool> ide_deshabilitar { get; set; }
        public string ide_cod_documento { get; set; }
    
        public virtual iso_empresa iso_empresa { get; set; }
    }
}
