//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_historia_clinica
    {
        public iso_historia_clinica()
        {
            this.iso_consulta_medica = new HashSet<iso_consulta_medica>();
        }
    
        public int ihc_id_historia { get; set; }
        public int ihc_id_personal { get; set; }
        public string ihc_id_empresa { get; set; }
        public string ihc_lugar_historia_clinica { get; set; }
        public Nullable<System.DateTime> ihc_fecha_historia_clinica { get; set; }
    
        public virtual ICollection<iso_consulta_medica> iso_consulta_medica { get; set; }
        public virtual iso_personal iso_personal { get; set; }
    }
}
