//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_sintoma
    {
        public iso_sintoma()
        {
            this.iso_sintoma_consulta_m = new HashSet<iso_sintoma_consulta_m>();
        }
    
        public int ist_id_sintoma { get; set; }
        public int ist_id_tipo_sintoma { get; set; }
        public string ist_nombre_sintoma { get; set; }
    
        public virtual ICollection<iso_sintoma_consulta_m> iso_sintoma_consulta_m { get; set; }
        public virtual iso_tipo_sintoma iso_tipo_sintoma { get; set; }
    }
}
