//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iso_cargo
    {
        public iso_cargo()
        {
            this.iso_puesto_trabajo = new HashSet<iso_puesto_trabajo>();
            this.iso_personal = new HashSet<iso_personal>();
            this.iso_matriz_profesiograma = new HashSet<iso_matriz_profesiograma>();
            this.iso_departamento = new HashSet<iso_departamento>();
        }
    
        public int icg_id_cargo { get; set; }
        [Display(Name = "Nombre")]
        [Required]
        public string icg_nombre { get; set; }
        [Display(Name = "Descripción")]
        public string icg_descripcion { get; set; }
        [Display(Name = "Código")]
        public Nullable<int> icg_cod_clase_cargo { get; set; }
        [Display(Name = "Nro. Trajadores")]
        public Nullable<int> icg_num_trabajadores { get; set; }
        [Display(Name = "Departamento")]
        public string icg_area { get; set; }
        [Display(Name = "Jefe Inmediato")]
        public string icg_jefe_inmediato { get; set; }
        [Display(Name = "Edad")]
        public string icg_edad { get; set; }
        [Display(Name = "Género")]
        public string icg_genero { get; set; }
        [Display(Name = "Instrucción")]
        public string icg_instruccion { get; set; }
        [Display(Name = "Experencia")]
        public string icg_experiencia { get; set; }
        [Display(Name = "Conocimiento Adicional")]
        public string icg_conocimiento_adicional { get; set; }
    
        public virtual ICollection<iso_puesto_trabajo> iso_puesto_trabajo { get; set; }
        public virtual ICollection<iso_personal> iso_personal { get; set; }
        public virtual ICollection<iso_matriz_profesiograma> iso_matriz_profesiograma { get; set; }
        public virtual ICollection<iso_departamento> iso_departamento { get; set; }
    }
}
