//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_empresa
    {
        public iso_empresa()
        {
            this.iso_departamento = new HashSet<iso_departamento>();
        }
    
        public int iem_cod_empresa { get; set; }
        public string iem_nombre_empresa { get; set; }
        public string iem_nemonico_empresa { get; set; }
        public string iem_ruc_empresa { get; set; }
        public string iem_direccion_empresa { get; set; }
        public string iem_telefono_empresa { get; set; }
        public string iem_rep_legal_empresa { get; set; }
        public string iem_personeria_empresa { get; set; }
        public string iem_icono_empresa { get; set; }
        public string iem_vision_empresa { get; set; }
        public string iem_mision_empresa { get; set; }
        public string iem_politica_empresa { get; set; }
        public string iem_objetivo_empresa { get; set; }
        public string iem_valores_empresa { get; set; }
        public byte[] iem_icono_archivo { get; set; }
        public string iem_politica_general { get; set; }
        public string iem_politica_calidad { get; set; }
        public string iem_estrategia_general { get; set; }
        public string iem_razon_social { get; set; }
        public string iem_numero_patronal { get; set; }
        public string iem_actividad { get; set; }
        public Nullable<int> iem_numero_trab_administrativos { get; set; }
        public Nullable<int> iem_numero_trab_planta { get; set; }
    
        public virtual ICollection<iso_departamento> iso_departamento { get; set; }
    }
}
