//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_riesgo_mrl
    {
        public iso_riesgo_mrl()
        {
            this.iso_detalle_matriz_mrl = new HashSet<iso_detalle_matriz_mrl>();
        }
    
        public int irm_id_riesgo { get; set; }
        public int irm_tipo_riesgo { get; set; }
        public string irm_nombre_riesgo { get; set; }
        public string irm_descripcion_riesgo { get; set; }
        public string irm_codigo_riesgo { get; set; }
    
        public virtual ICollection<iso_detalle_matriz_mrl> iso_detalle_matriz_mrl { get; set; }
        public virtual iso_tipo_riesgo_ocupacional iso_tipo_riesgo_ocupacional { get; set; }
    }
}
