//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_sindrome
    {
        public iso_sindrome()
        {
            this.iso_sindrome_consulta_m = new HashSet<iso_sindrome_consulta_m>();
        }
    
        public int iso_id_sindrome { get; set; }
        public string iso_nombre_sindrome { get; set; }
    
        public virtual ICollection<iso_sindrome_consulta_m> iso_sindrome_consulta_m { get; set; }
    }
}
