//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iso_usuario
    {
        public iso_usuario()
        {
            this.iso_modulo = new HashSet<iso_modulo>();
        }
    
        public int ius_id_usuario { get; set; }
        [Display(Name = "Nombre")]
        [Required]
        public string ius_nombre_usuario { get; set; }
        [Display(Name = "Descripción")]
        [Required]
        public string ius_desc_usuario { get; set; }
        [Display(Name = "Usuario")]
        [Required]
        public string ius_login { get; set; }
        [Display(Name = "Clave")]
        [Required]
        public string ius_password { get; set; }
        public byte ius_permisos { get; set; }
        public Nullable<int> ius_id_departamento { get; set; }
        public string ius_iniciales { get; set; }
        public string ius_email { get; set; }
        public string ius_firma_digital { get; set; }
        public string ius_deshabilitado { get; set; }
        public byte[] ius_firma_archivo { get; set; }
        public string ius_representante_direccion { get; set; }
        public string ius_miembro_comite { get; set; }
        public string ius_foto_ruta { get; set; }
        public byte[] ius_foto_archivo { get; set; }
        public string ius_tipo_usuario { get; set; }
        public Nullable<byte> ius_carga_documento { get; set; }
    
        public virtual ICollection<iso_modulo> iso_modulo { get; set; }
    }
}
