//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_tipo_exam_fisico
    {
        public iso_tipo_exam_fisico()
        {
            this.iso_exam_fisico_parametro = new HashSet<iso_exam_fisico_parametro>();
        }
    
        public int ite_id_tipo_ef { get; set; }
        public string ite_nombre_tipo_ef { get; set; }
        public Nullable<int> ite_id_tipo_efpadre { get; set; }
    
        public virtual ICollection<iso_exam_fisico_parametro> iso_exam_fisico_parametro { get; set; }
    }
}
