//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_exam_fisico_parametro
    {
        public iso_exam_fisico_parametro()
        {
            this.iso_exam_fp_consulta_m = new HashSet<iso_exam_fp_consulta_m>();
        }
    
        public int ief_id_examen_fis { get; set; }
        public int ief_tipo_examen { get; set; }
        public string ief_nombre_examen { get; set; }
    
        public virtual iso_tipo_exam_fisico iso_tipo_exam_fisico { get; set; }
        public virtual ICollection<iso_exam_fp_consulta_m> iso_exam_fp_consulta_m { get; set; }
    }
}
