//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_equipo_proteccion
    {
        public iso_equipo_proteccion()
        {
            this.iso_equipo_caracteristica = new HashSet<iso_equipo_caracteristica>();
            this.iso_puesto_trabajo = new HashSet<iso_puesto_trabajo>();
        }
    
        public int iep_id_equipo_p { get; set; }
        public string iep_nombre_equipo_p { get; set; }
        public string iep_ubic_imagen_equipo_p { get; set; }
        public byte[] iep_imagen_equipo_p { get; set; }
        public Nullable<int> iep_stock { get; set; }
    
        public virtual ICollection<iso_equipo_caracteristica> iso_equipo_caracteristica { get; set; }
        public virtual ICollection<iso_puesto_trabajo> iso_puesto_trabajo { get; set; }
    }
}
