//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_sindrome_consulta_m
    {
        public int isd_id_sindrome { get; set; }
        public int isd_id_historia_clinica { get; set; }
        public int isd_id_personal { get; set; }
        public int isd_id_consulta_medica { get; set; }
        public string isd_descripcion { get; set; }
    
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
        public virtual iso_sindrome iso_sindrome { get; set; }
    }
}
