//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iso_exam_fp_consulta_m
    {
        public int iec_id_consulta_medica { get; set; }
        public int iec_id_historia_clinica { get; set; }
        public int iec_id_personal { get; set; }
        [Display(Name = "Nombre")]
        [Required]
        public int iec_id_exam_fisico { get; set; }
        [Display(Name = "Tipo")]
        [Required]
        public int iec_id_tipo_exam_fisico { get; set; }
        public string iec_campo1 { get; set; }
        public string iec_campo2 { get; set; }
        public string iec_campo3 { get; set; }
        public string iec_campo4 { get; set; }
        public string iec_campo5 { get; set; }
    
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
        public virtual iso_exam_fisico_parametro iso_exam_fisico_parametro { get; set; }
    }
}
