//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_permiso_medico
    {
        public int ipm_id_permiso_med { get; set; }
        public Nullable<int> ipm_id_historia { get; set; }
        public Nullable<int> ipm_id_consulta { get; set; }
        public Nullable<int> ipm_id_personal { get; set; }
        public Nullable<int> ipm_id_tipo_permisom { get; set; }
        public Nullable<System.DateTime> ipm_fecha_permiso_ini { get; set; }
        public Nullable<System.DateTime> ipm_fecha_permiso_fin { get; set; }
        public Nullable<int> ipm_dias_permiso { get; set; }
    
        public virtual iso_consulta_medica iso_consulta_medica { get; set; }
    }
}
