//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_detalle_matriz_ocupacional
    {
        public int idm_id_matriz_ocupacional { get; set; }
        public int idm_id_riesgo_ocupacional { get; set; }
        public int idm_tipo_riesgo_ocupacional { get; set; }
        public string idm_probabilidad { get; set; }
        public string idm_consecuencia { get; set; }
        public string idm_estimacion { get; set; }
    
        public virtual iso_matriz_riesgo_ocupacional iso_matriz_riesgo_ocupacional { get; set; }
        public virtual iso_riesgo_ocupacional iso_riesgo_ocupacional { get; set; }
    }
}
