//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBM_SART.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iso_puesto_trabajo
    {
        public iso_puesto_trabajo()
        {
            this.iso_cargo = new HashSet<iso_cargo>();
            this.iso_personal = new HashSet<iso_personal>();
            this.iso_personal1 = new HashSet<iso_personal>();
        }
    
        public int ipt_id_puesto_t { get; set; }
        public string ipt_nombre_puesto_t { get; set; }
        public string ipt_descrip_puesto_t { get; set; }
        public Nullable<int> ipt_nro_trbajadores { get; set; }
    
        public virtual ICollection<iso_cargo> iso_cargo { get; set; }
        public virtual ICollection<iso_personal> iso_personal { get; set; }
        public virtual ICollection<iso_personal> iso_personal1 { get; set; }
    }
}
